---
default_base_path: /opt/unique
default_client_version: v25090091
default_database: rocksdb
default_database_path: "{{ default_base_path }}/chains"
default_download_base_url: https://github.com/UniqueNetwork/unique-chain/releases/download
default_download_url: "{{ default_download_base_url }}/{{ default_client_version }}/unique-collator-{{ default_client_version }}"
default_user: "{{ service_users['unique'] }}"
default_group: "{{ service_users['unique'] }}"
default_log_level: info
default_network: unique
default_node_type: endpoint
#havent touch below
#NOTE: please check it
default_p2p_port_ws: 30434
default_p2p_port_wss: 30435
default_bootnode_p2p_port_ws: 30434
default_bootnode_p2p_port_wss: 30435
default_prom_port: 7400
default_rpc_port: 9400
default_secure_rpc_port: 42800
default_service: unique
default_storage: "{{ default_base_path }}/chains"
default_telemetry_url: wss://telemetry-backend.w3f.community/submit/ 1
zabbix_ext_port: 10800
