---
default_base_path: /opt/zebra
default_database_path: /opt/zebra/state
default_client_version: "2.2.0"
default_user: "{{ service_users['zebra'] }}"
default_group: "{{ service_users['zebra'] }}"
default_network: "Mainnet"
default_p2p_port: 8233
default_rpc_port: 8232
default_prom_port: 9999
default_in_peers: 50
default_out_peers: 50
