# Standards: 0.2
---
galaxy_info:
  author: Rotko Networks <hq@rotko.net>
  description: Setup P2P networking
  min_ansible_version: 3.0
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
dependencies:
  - setup_add_node_role
