---
ansible_host: "160.22.181.181"
container_ip: "192.168.122.15"
ansible_port: 2828
host_name: "rpc-coretime-kusama-02.ct.rotko.net"
host_timezone: "Asia/Bangkok"
# netif: '{"net0":"name=eth0,gw={{ default_nat_network_forward_cidr.split("/")[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"}'
netif:
  net0: "name=eth0,gw={{ default_nat_network_forward_cidr.split('/')[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"
  net1: "name=eth1,gw={{ default_host_internal_ip }},ip=10.7.122.15/16,bridge={{ default_host_internal_bridge }}"
container_internal_ip: "10.7.122.15"
role: "cumulus"
pinned_service: False

default_telemetry_name: "Rotko Networks - {{ host_name.split('.')[0] }} {{ default_node_type | capitalize }}"
default_domain: "{{ host_name }}"
default_network: "coretime-kusama"
default_relay_rpc: "ws://{{ hostvars['rpc-kusama-01']['container_ip'] }}:{{ hostvars['rpc-kusama-01']['default_rpc_port'] }}"
default_relay_rpc_fallback: "ws://{{ hostvars['rpc-kusama-02']['container_ip'] }}:{{ hostvars['rpc-kusama-02']['default_rpc_port'] }}"
default_database: rocksdb
default_node_type: "endpoint"

default_bootnode_domain: "{{ default_network }}.boot.rotko.net"

default_p2p_port: 32052
default_bootnode_p2p_port: 32052
default_bootnode_p2p_port_ws: 30434
default_bootnode_p2p_port_wss: 30435

default_secure_rpc_port: 42828
zabbix_ext_port: 10828
