---
ansible_host: "160.22.181.181"
container_ip: "192.168.111.12"
ansible_port: 2641
host_name: "rpc-bridge-hub-polkadot-01.ct.rotko.net"
host_timezone: "Asia/Bangkok"
# netif: '{"net0":"name=eth0,gw={{ default_nat_network_forward_cidr.split("/")[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"}'
netif:
  net0: "name=eth0,gw={{ default_nat_network_forward_cidr.split('/')[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"
  net1: "name=eth1,gw={{ default_host_internal_ip }},ip=10.6.111.12/16,bridge={{ default_host_internal_bridge }}"
container_internal_ip: "10.6.111.12"
role: "cumulus"
pinned_service: True

default_telemetry_name: "Rotko Networks - {{ host_name.split('.')[0] }}"
default_domain: "{{ host_name }}"
default_network: "bridge-hub-polkadot"
default_relay_rpc: "ws://{{ hostvars['rpc-polkadot-01']['container_ip'] }}:{{ hostvars['rpc-polkadot-01']['default_rpc_port'] }}"
default_relay_rpc_fallback: "ws://{{ hostvars['rpc-polkadot-02']['container_ip'] }}:{{ hostvars['rpc-polkadot-02']['default_rpc_port'] }}"
default_database: "rocksdb"
default_node_type: "endpoint"
zabbix_ext_port: 10641

transition_bootnode_domain: "pbr13.rotko.net"
transition_bootnode_p2p_port: 33543
transition_bootnode_p2p_port_ws: 34543
transition_bootnode_p2p_port_wss: 35543

default_p2p_port: 31021
default_bootnode_domain: "{{ default_network }}.boot.rotko.net"
default_bootnode_p2p_port: 31021
default_bootnode_p2p_port_ws: 30434
default_bootnode_p2p_port_wss: 30435
default_secure_rpc_port: 42641
