---
ansible_host: "160.22.181.181"
container_ip: "192.168.141.17"
ansible_port: 3147
host_name: "rpc-passet-hub-paseo-01.ct.rotko.net"
host_timezone: "Asia/Bangkok"
# netif: '{"net0":"name=eth0,gw={{ default_nat_network_forward_cidr.split("/")[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"}'
netif:
  net0: "name=eth0,gw={{ default_nat_network_forward_cidr.split('/')[0] }},ip={{ default_mgmt_host_ip }}/16,bridge={{ default_nat_device }}"
  net1: "name=eth1,gw={{ default_host_internal_ip }},ip=10.7.141.17/16,bridge={{ default_host_internal_bridge }}"
container_internal_ip: "10.7.141.17"
role: "cumulus"
pinned_service: True
need_revive_rpc: True
revive_rpc_version: polkadot-unstable2507-revive

default_telemetry_name: "Rotko Networks - {{ host_name.split('.')[0] }}"
default_domain: "{{ host_name }}"
default_network: "passet-hub-paseo"
default_chain_spec: "{{ default_base_path }}/passet-hub-paseo.raw.json"
# default_chain_spec_dl_url: "https://raw.githubusercontent.com/paseo-network/passet-hub/refs/heads/main/genesis/passet_hub.raw.json"
default_chain_spec_dl_url: "https://raw.githubusercontent.com/paritytech/chainspecs/refs/heads/main/paseo/parachain/passet-hub/chainspec.json"
default_relay_rpc: "ws://{{ hostvars['rpc-paseo-01']['container_ip'] }}:{{ hostvars['rpc-paseo-01']['default_rpc_port'] }}"
default_relay_rpc_fallback: "ws://{{ hostvars['rpc-paseo-02']['container_ip'] }}:{{ hostvars['rpc-paseo-02']['default_rpc_port'] }}"
default_database: "rocksdb"
default_node_type: "endpoint"
default_p2p_port: 34071
default_secure_rpc_port: 42071
default_rpc_port: 9400
default_prom_port: 7400
zabbix_ext_port: 10971

default_bootnode_domain: "{{ default_network }}.rotko.net"
default_bootnode_p2p_port: 34071
default_bootnode_p2p_port_ws: 30434
default_bootnode_p2p_port_wss: 30435
