# Standards: 0.2
---
- name: Default tools and configurations
  hosts: polkadot
  gather_facts: True
  roles:
    - setup_add_node_role
    # - setup_install_rust
    # - setup_install_promtail
    # - setup_install_fluent_bit
    - setup_networking_p2p
    - setup_install_polkadot
    - setup_install_nginx
